version: '3'
services:

  mysqldb:
    image: mysql:8.1
    env_file:
      - ./.env
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}"
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}

  target100-backend:
    # image: transvisionsolutions/transvision-data-manager:1.0.0.42
    build: 
      context: ../RankingSystem
      dockerfile: Dockerfile
    
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}
      - spring.datasource.username=root
      - spring.datasource.password=${MYSQLDB_ROOT_PASSWORD}
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.show-sql:true
      - spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
      - server.ui.url=http://13.201.167.118:3000
      
      
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  ranking-system-ui:
    # image: transvisionsolutions/transvision-ui-portal:1.0.0.347
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./.env
    ports:
      - "${UI_LOCAL_PORT}:${UI_DOCKER_PORT}"
    environment:
      - REACT_APP_API_URL=https://thetarget100.com
    networks:
      - springmysql-net
    depends_on:
      - target100-backend

networks:
  springmysql-net:
